// Code generated by 'guts'. DO NOT EDIT.

// From api/types.go
enum AccessScope {
    AccessScopeBroad = "broad",
    AccessScopeCustom = "custom",
    AccessScopeHTTP = "http",
    AccessScopeLimited = "limited",
    AccessScopeNone = "none",
    AccessScopeSSH = "ssh",
    AccessScopeUnknown = ""
}

// From api/types.go
interface CloudAuthRequest {
    tailnet: string;
    apiKey: string;
}

// From api/types.go
interface CloudAuthStatusResponse {
    authenticated: boolean;
    tailnet?: string;
    hasPolicy: boolean;
}

// From api/types.go
interface Device {
    id: string;
    name: string;
    ip: string;
    tailscaleIps: string[];
    os: string;
    online: boolean;
    owner: string;
    tags: string[];
    subnetRouter: boolean;
    routedSubnets: string[];
    lastSeen?: string;
}

// From api/types.go
interface Edge {
    id: string;
    from: string;
    to: string;
    kind: EdgeKind;
    labels?: string[];
    protocols?: string[];
    ports?: string[];
    accessScope?: AccessScope;
    policyRefs?: PolicyRef[];
    perspectives?: string[];
}

// From api/types.go
enum EdgeKind {
    EdgeKindACL = "acl",
    EdgeKindOwner = "owner",
    EdgeKindSubnet = "subnet",
    EdgeKindTag = "tag"
}

// From api/types.go
interface ErrorResponse {
    error: string;
}

// From api/types.go
interface HealthResponse {
    status: string;
    version: string;
}

// From api/types.go
interface LocalAPIStatusResponse {
    available: boolean;
    localApiEndpoint: string;
    error?: string;
}

// From api/types.go
interface PolicyRef {
    section: string;
    index: number;
    src?: string;
    dst?: string;
}

// From api/types.go
interface PolicyResponse {
    tailnet: string;
    hujson: string;
}

// From api/types.go
interface SocketMessage {
    type: string;
    requestId?: string;
    // empty interface{} type, falling back to unknown
    payload?: unknown;
}

// From api/types.go
const SocketMessageLocalAPIUnavailable = "localapi.unavailable";

// From api/types.go
const SocketMessageTopologySnapshot = "topology.snapshot";

// From api/types.go
interface TopologyResponse {
    devices: Device[];
    edges: Edge[];
}

