// Code generated by 'guts'. DO NOT EDIT.

// From api/types.go
interface Device {
    id: string;
    name: string;
    ip: string;
    tailscaleIps: string[];
    os: string;
    online: boolean;
    owner: string;
    tags: string[];
    subnetRouter: boolean;
    routedSubnets: string[];
    lastSeen?: string;
}

// From api/types.go
interface Edge {
    id: string;
    from: string;
    to: string;
    kind: EdgeKind;
    labels?: string[];
}

// From api/types.go
enum EdgeKind {
    EdgeKindACL = "acl",
    EdgeKindOwner = "owner",
    EdgeKindSubnet = "subnet",
    EdgeKindTag = "tag"
}

// From api/types.go
interface HealthResponse {
    status: string;
    version: string;
}

// From api/types.go
interface LocalAPIStatusResponse {
    available: boolean;
    socketPath: string;
    error?: string;
}

// From api/types.go
interface TopologyResponse {
    devices: Device[];
    edges: Edge[];
}

