// This file is auto-generated by @hey-api/openapi-ts

export { getHealth, getStatus, getTailnet, getTopology, type Options } from './sdk.gen';
export type { ClientOptions, Device, Edge, EdgeKind, GetHealthData, GetHealthResponse, GetHealthResponses, GetStatusData, GetStatusResponse, GetStatusResponses, GetTailnetData, GetTailnetError, GetTailnetErrors, GetTailnetResponse, GetTailnetResponses, GetTopologyData, GetTopologyResponse, GetTopologyResponses, HealthResponse, LocalApiStatusResponse, TopologyResponse } from './types.gen';
