// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthenticateCloudData, AuthenticateCloudErrors, AuthenticateCloudResponses, DraftPolicyAclRuleData, DraftPolicyAclRuleErrors, DraftPolicyAclRuleResponses, GetCloudStatusData, GetCloudStatusResponses, GetHealthData, GetHealthResponses, GetPolicyData, GetPolicyErrors, GetPolicyMapData, GetPolicyMapErrors, GetPolicyMapResponses, GetPolicyResponses, GetStatusData, GetStatusResponses, GetTopologyData, GetTopologyErrors, GetTopologyResponses, SaveValidatedPolicyDraftData, SaveValidatedPolicyDraftErrors, SaveValidatedPolicyDraftResponses, ValidatePolicyDraftData, ValidatePolicyDraftErrors, ValidatePolicyDraftResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

export const getTopology = <ThrowOnError extends boolean = false>(options?: Options<GetTopologyData, ThrowOnError>) => (options?.client ?? client).get<GetTopologyResponses, GetTopologyErrors, ThrowOnError>({ url: '/api/topology', ...options });

export const getStatus = <ThrowOnError extends boolean = false>(options?: Options<GetStatusData, ThrowOnError>) => (options?.client ?? client).get<GetStatusResponses, unknown, ThrowOnError>({ url: '/api/status', ...options });

export const getCloudStatus = <ThrowOnError extends boolean = false>(options?: Options<GetCloudStatusData, ThrowOnError>) => (options?.client ?? client).get<GetCloudStatusResponses, unknown, ThrowOnError>({ url: '/api/cloud/status', ...options });

export const authenticateCloud = <ThrowOnError extends boolean = false>(options: Options<AuthenticateCloudData, ThrowOnError>) => (options.client ?? client).post<AuthenticateCloudResponses, AuthenticateCloudErrors, ThrowOnError>({
    url: '/api/cloud/auth',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getPolicy = <ThrowOnError extends boolean = false>(options?: Options<GetPolicyData, ThrowOnError>) => (options?.client ?? client).get<GetPolicyResponses, GetPolicyErrors, ThrowOnError>({ url: '/api/policy', ...options });

export const getPolicyMap = <ThrowOnError extends boolean = false>(options?: Options<GetPolicyMapData, ThrowOnError>) => (options?.client ?? client).get<GetPolicyMapResponses, GetPolicyMapErrors, ThrowOnError>({ url: '/api/policy/map', ...options });

export const draftPolicyAclRule = <ThrowOnError extends boolean = false>(options: Options<DraftPolicyAclRuleData, ThrowOnError>) => (options.client ?? client).post<DraftPolicyAclRuleResponses, DraftPolicyAclRuleErrors, ThrowOnError>({
    url: '/api/policy/draft',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const validatePolicyDraft = <ThrowOnError extends boolean = false>(options: Options<ValidatePolicyDraftData, ThrowOnError>) => (options.client ?? client).post<ValidatePolicyDraftResponses, ValidatePolicyDraftErrors, ThrowOnError>({
    url: '/api/policy/validate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const saveValidatedPolicyDraft = <ThrowOnError extends boolean = false>(options?: Options<SaveValidatedPolicyDraftData, ThrowOnError>) => (options?.client ?? client).post<SaveValidatedPolicyDraftResponses, SaveValidatedPolicyDraftErrors, ThrowOnError>({ url: '/api/policy/save', ...options });
