// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetHealthData, GetHealthResponses, GetStatusData, GetStatusResponses, GetTailnetData, GetTailnetErrors, GetTailnetResponses, GetTopologyData, GetTopologyResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

export const getTopology = <ThrowOnError extends boolean = false>(options?: Options<GetTopologyData, ThrowOnError>) => (options?.client ?? client).get<GetTopologyResponses, unknown, ThrowOnError>({ url: '/api/topology', ...options });

export const getStatus = <ThrowOnError extends boolean = false>(options?: Options<GetStatusData, ThrowOnError>) => (options?.client ?? client).get<GetStatusResponses, unknown, ThrowOnError>({ url: '/api/status', ...options });

export const getTailnet = <ThrowOnError extends boolean = false>(options?: Options<GetTailnetData, ThrowOnError>) => (options?.client ?? client).get<GetTailnetResponses, GetTailnetErrors, ThrowOnError>({ url: '/api/tailnet', ...options });
