// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type HealthResponse = {
    status: string;
    version: string;
};

export type LocalApiStatusResponse = {
    available: boolean;
    localApiEndpoint: string;
    error?: string;
};

export type Device = {
    id: string;
    name: string;
    ip: string;
    tailscaleIps: Array<string>;
    os: string;
    online: boolean;
    owner: string;
    tags: Array<string>;
    subnetRouter: boolean;
    routedSubnets: Array<string>;
    lastSeen?: string;
};

export type EdgeKind = 'owner' | 'tag' | 'subnet' | 'acl';

export type Edge = {
    id: string;
    from: string;
    to: string;
    kind: EdgeKind;
    labels?: Array<string>;
};

export type TopologyResponse = {
    devices: Array<Device>;
    edges: Array<Edge>;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetHealthResponses = {
    /**
     * Server health.
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetTopologyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/topology';
};

export type GetTopologyErrors = {
    /**
     * Tailscale LocalAPI is unavailable.
     */
    503: LocalApiStatusResponse;
};

export type GetTopologyError = GetTopologyErrors[keyof GetTopologyErrors];

export type GetTopologyResponses = {
    /**
     * Current tailnet topology snapshot. The topology socket sends the same shape as a topology.snapshot payload.
     */
    200: TopologyResponse;
};

export type GetTopologyResponse = GetTopologyResponses[keyof GetTopologyResponses];

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/status';
};

export type GetStatusResponses = {
    /**
     * LocalAPI connectivity status.
     */
    200: LocalApiStatusResponse;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];
