// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type HealthResponse = {
    status: string;
    version: string;
};

export type Device = {
    id: string;
    name: string;
    ip: string;
    os: string;
    online: boolean;
    owner: string;
    tags: Array<string>;
    lastSeen?: string;
};

export type EdgeKind = 'owner' | 'tag' | 'acl';

export type Edge = {
    id: string;
    from: string;
    to: string;
    kind: EdgeKind;
    labels?: Array<string>;
};

export type TopologyResponse = {
    devices: Array<Device>;
    edges: Array<Edge>;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetHealthResponses = {
    /**
     * Server health.
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetTopologyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/topology';
};

export type GetTopologyResponses = {
    /**
     * Tailnet topology graph.
     */
    200: TopologyResponse;
};

export type GetTopologyResponse = GetTopologyResponses[keyof GetTopologyResponses];
