// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type HealthResponse = {
    status: string;
    version: string;
};

export type LocalApiStatusResponse = {
    available: boolean;
    localApiEndpoint: string;
    error?: string;
};

export type Device = {
    id: string;
    name: string;
    ip: string;
    tailscaleIps: Array<string>;
    os: string;
    online: boolean;
    owner: string;
    tags: Array<string>;
    subnetRouter: boolean;
    routedSubnets: Array<string>;
    lastSeen?: string;
};

export type EdgeKind = 'owner' | 'tag' | 'subnet' | 'acl';

export type Edge = {
    id: string;
    from: string;
    to: string;
    kind: EdgeKind;
    labels?: Array<string>;
    protocols?: Array<string>;
    ports?: Array<string>;
    accessScope?: AccessScope;
    policyRefs?: Array<PolicyRef>;
    perspectives?: Array<string>;
};

export type AccessScope = 'ssh' | 'http' | 'broad' | 'custom' | 'limited' | 'none';

export type PolicyRef = {
    section: string;
    index: number;
    src?: string;
    dst?: string;
};

export type TopologyResponse = {
    devices: Array<Device>;
    edges: Array<Edge>;
};

export type CloudAuthRequest = {
    tailnet: string;
    apiKey: string;
};

export type CloudAuthStatusResponse = {
    authenticated: boolean;
    tailnet?: string;
    hasPolicy: boolean;
};

export type PolicyResponse = {
    tailnet: string;
    hujson: string;
};

export type ErrorResponse = {
    error: string;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetHealthResponses = {
    /**
     * Server health.
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetTopologyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/topology';
};

export type GetTopologyErrors = {
    /**
     * Tailscale LocalAPI is unavailable.
     */
    503: LocalApiStatusResponse;
};

export type GetTopologyError = GetTopologyErrors[keyof GetTopologyErrors];

export type GetTopologyResponses = {
    /**
     * Current tailnet topology snapshot. The topology socket sends the same shape as a topology.snapshot payload.
     */
    200: TopologyResponse;
};

export type GetTopologyResponse = GetTopologyResponses[keyof GetTopologyResponses];

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/status';
};

export type GetStatusResponses = {
    /**
     * LocalAPI connectivity status.
     */
    200: LocalApiStatusResponse;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type GetCloudStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/cloud/status';
};

export type GetCloudStatusResponses = {
    /**
     * Cloud API authentication status.
     */
    200: CloudAuthStatusResponse;
};

export type GetCloudStatusResponse = GetCloudStatusResponses[keyof GetCloudStatusResponses];

export type AuthenticateCloudData = {
    body: CloudAuthRequest;
    path?: never;
    query?: never;
    url: '/api/cloud/auth';
};

export type AuthenticateCloudErrors = {
    /**
     * Invalid auth request.
     */
    400: ErrorResponse;
    /**
     * Tailscale Cloud API request failed.
     */
    502: ErrorResponse;
};

export type AuthenticateCloudError = AuthenticateCloudErrors[keyof AuthenticateCloudErrors];

export type AuthenticateCloudResponses = {
    /**
     * API key authentication succeeded and policy was fetched.
     */
    200: CloudAuthStatusResponse;
};

export type AuthenticateCloudResponse = AuthenticateCloudResponses[keyof AuthenticateCloudResponses];

export type GetPolicyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/policy';
};

export type GetPolicyErrors = {
    /**
     * Cloud API authentication has not been enabled.
     */
    401: ErrorResponse;
    /**
     * Tailscale Cloud API request failed.
     */
    502: ErrorResponse;
};

export type GetPolicyError = GetPolicyErrors[keyof GetPolicyErrors];

export type GetPolicyResponses = {
    /**
     * Current tailnet policy file as raw HuJSON.
     */
    200: PolicyResponse;
};

export type GetPolicyResponse = GetPolicyResponses[keyof GetPolicyResponses];
